
services:
  currency_api:
    image: currency_api
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    network_mode: host

volumes:
  pgdata:
